DATASET:
  TRAIN:
    TYPE: 'ConcatDataset'
    SET_LIST:
      - TYPE: 'Mscoco'
        MASK_ID: 0
        ROOT: './'
        IMG_PREFIX: 'train2017'
        ANN: 'data/annotations/person_keypoints_train2017.json'
        AUG:
          FLIP: true
          ROT_FACTOR: 40
          SCALE_FACTOR: 0.3
          NUM_JOINTS_HALF_BODY: 8
          PROB_HALF_BODY: -1
      - TYPE: 'Mpii'
        MASK_ID: 17
        ROOT: './data/mpii/'
        IMG_PREFIX: 'images'
        ANN: 'annot_mpii.json'
        AUG:
          FLIP: true
          ROT_FACTOR: 40
          SCALE_FACTOR: 0.3
          NUM_JOINTS_HALF_BODY: 8
          PROB_HALF_BODY: -1
  VAL:
    TYPE: 'Mscoco'
    ROOT: './'
    IMG_PREFIX: 'val2017'
    ANN: 'data/annotations/person_keypoints_val2017.json'
  TEST:
    TYPE: 'Mscoco_det'
    ROOT: './'
    IMG_PREFIX: 'val2017'
    DET_FILE: './exp/json/test_det_yolo.json'
    ANN: ''
DATA_PRESET:
  TYPE: 'simple'
  SIGMA: 2
  NUM_JOINTS: 33
  IMAGE_SIZE:
  - 256
  - 192
  HEATMAP_SIZE:
  - 64
  - 48
MODEL:
  TYPE: 'FastPose'
  # Trouble shooting 
  # size mismatch for conv_out.weight:
  # size mismatch for conv_out.bias:
  # ==> Pretrained : weight만 가지고옴.
  # ==> (Check?) Try_load : 외부 model을 빌드를 할 수 있게 함.


  PRETRAINED: './pretrained_models/coco_wholebody133_fast50_regression_256x192.pth'
  TRY_LOAD: ''
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_LAYERS: 50
LOSS:
  TYPE: 'MSELoss'
DETECTOR: # 건들지 안흔다.
  NAME: 'yolo'
  CONFIG: 'detector/yolo/cfg/yolov3-spp.cfg'
  WEIGHTS: 'detector/yolo/data/yolov3-spp.weights'
  NMS_THRES: 0.6
  CONFIDENCE: 0.05
TRAIN:
  WORLD_SIZE: 4
  BATCH_SIZE: 32
  BEGIN_EPOCH: 0
  END_EPOCH: 200
  OPTIMIZER: 'adam'
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP:
  - 90
  - 120
  DPG_MILESTONE: 140
  DPG_STEP:
  - 160
  - 190